-- MySQL Script generated by MySQL Workbench
-- Thu Jun  3 18:27:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotify` DEFAULT CHARACTER SET utf8 ;
USE `Spotify` ;

-- -----------------------------------------------------
-- Table `Spotify`.`Pista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Pista` (
  `idPista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `duracion` FLOAT NOT NULL,
  `popularidad` INT NULL,
  `genero` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Podcast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Podcast` (
  `descripcion` VARCHAR(100) NOT NULL,
  `Pista_idPista` INT NOT NULL,
  INDEX `fk_Podcast_Pista1_idx` (`Pista_idPista` ASC),
  PRIMARY KEY (`Pista_idPista`),
  CONSTRAINT `fk_Podcast_Pista1`
    FOREIGN KEY (`Pista_idPista`)
    REFERENCES `Spotify`.`Pista` (`idPista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Cancion` (
  `Pista_idPista` INT NOT NULL,
  INDEX `fk_Cancion_Pista_idx` (`Pista_idPista` ASC),
  PRIMARY KEY (`Pista_idPista`),
  CONSTRAINT `fk_Cancion_Pista`
    FOREIGN KEY (`Pista_idPista`)
    REFERENCES `Spotify`.`Pista` (`idPista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `playlist_creadas` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Playlist` (
  `idPlaylist` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad_pistas` INT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Creador_Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPlaylist`),
  INDEX `fk_Playlist_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Playlist_Creador1_idx` (`Creador_Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Playlist_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist_Creador1`
    FOREIGN KEY (`Creador_Usuario_idUsuario`)
    REFERENCES `Spotify`.`Creador` (`Usuario_idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Creador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Creador` (
  `pistas_creadas` INT NOT NULL DEFAULT 0,
  `Usuario_idUsuario` INT NOT NULL,
  `Playlist_idPlaylist` INT NOT NULL,
  INDEX `fk_Creador_Usuario1_idx` (`Usuario_idUsuario` ASC),
  PRIMARY KEY (`Usuario_idUsuario`),
  INDEX `fk_Creador_Playlist1_idx` (`Playlist_idPlaylist` ASC),
  CONSTRAINT `fk_Creador_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Creador_Playlist1`
    FOREIGN KEY (`Playlist_idPlaylist`)
    REFERENCES `Spotify`.`Playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Consumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Consumidor` (
  `seguidores` INT NOT NULL DEFAULT 0,
  `seguidos` INT NOT NULL DEFAULT 0,
  `Usuario_idUsuario` INT NOT NULL,
  INDEX `fk_Consumidor_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Consumidor_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Consumir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Consumir` (
  `Playlist_idPlaylist` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  INDEX `fk_Consumir_Playlist1_idx` (`Playlist_idPlaylist` ASC),
  INDEX `fk_Consumir_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Consumir_Playlist1`
    FOREIGN KEY (`Playlist_idPlaylist`)
    REFERENCES `Spotify`.`Playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consumir_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Reproduce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Reproduce` (
  `Usuario_idUsuario` INT NOT NULL,
  `Pista_idPista` INT NOT NULL,
  INDEX `fk_Reproduce_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Reproduce_Pista1_idx` (`Pista_idPista` ASC),
  CONSTRAINT `fk_Reproduce_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Spotify`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reproduce_Pista1`
    FOREIGN KEY (`Pista_idPista`)
    REFERENCES `Spotify`.`Pista` (`idPista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Tiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`Tiene` (
  `Playlist_idPlaylist` INT NOT NULL,
  `Pista_idPista` INT NOT NULL,
  PRIMARY KEY (`Playlist_idPlaylist`, `Pista_idPista`),
  INDEX `fk_Playlist_has_Pista_Pista1_idx` (`Pista_idPista` ASC),
  INDEX `fk_Playlist_has_Pista_Playlist1_idx` (`Playlist_idPlaylist` ASC),
  CONSTRAINT `fk_Playlist_has_Pista_Playlist1`
    FOREIGN KEY (`Playlist_idPlaylist`)
    REFERENCES `Spotify`.`Playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist_has_Pista_Pista1`
    FOREIGN KEY (`Pista_idPista`)
    REFERENCES `Spotify`.`Pista` (`idPista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
